name: coffee_shop
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <=4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+4
  shared_preferences: ^2.2.2
  device_preview: ^1.1.0
  flutter_svg: ^0.22.0
  page_transition: ^2.0.2
  flutter_markdown: ^0.6.0
  sqflite: ^2.3.0
  path: ^1.8.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  english_words: ^4.0.0
  provider: ^6.1.1
  chat_gpt_sdk: ^2.2.8
  animated_bottom_navigation_bar: ^1.3.0
  audioplayers: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/font/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Bold.ttf # Sesuaikan dengan nama file sebenarnya
          weight: 700
        - asset: assets/font/Poppins-Medium.ttf # Sesuaikan dengan nama file sebenarnya
          weight: 500
        - asset: assets/font/Poppins-Regular.ttf # Sesuaikan dengan nama file sebenarnya
          weight: 300
