// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZlJ3jP5ZlNAaqeFLSa9rgY96XsxHJS-M',
    appId: '1:976902934256:web:d8ee71b7957b676218bc35',
    messagingSenderId: '976902934256',
    projectId: 'mycoffeeuser',
    authDomain: 'mycoffeeuser.firebaseapp.com',
    storageBucket: 'mycoffeeuser.appspot.com',
    measurementId: 'G-2PYWEYMYPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwAZIHUsZpPOgCCDFZi34Vlxtkww2OLzo',
    appId: '1:976902934256:android:923cfc1844b65a9e18bc35',
    messagingSenderId: '976902934256',
    projectId: 'mycoffeeuser',
    storageBucket: 'mycoffeeuser.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwSUcy-6sKtbMfCnAAA-0h1Ivo5MGr3Nw',
    appId: '1:976902934256:ios:8058f37519ddd75e18bc35',
    messagingSenderId: '976902934256',
    projectId: 'mycoffeeuser',
    storageBucket: 'mycoffeeuser.appspot.com',
    iosBundleId: 'com.example.coffeeShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwSUcy-6sKtbMfCnAAA-0h1Ivo5MGr3Nw',
    appId: '1:976902934256:ios:e727a4fea89d970018bc35',
    messagingSenderId: '976902934256',
    projectId: 'mycoffeeuser',
    storageBucket: 'mycoffeeuser.appspot.com',
    iosBundleId: 'com.example.coffeeShop.RunnerTests',
  );
}
